---
# Eslint configure #############################################################
################################################################################
# http://eslint.org/docs/user-guide/configuring
# YAML javascript 语法： http://nodeca.github.io/js-yaml/
# https://github.com/airbnb/javascript

extends: "airbnb-base" # 扩展
env:
  commonjs: true
rules:
  semi:
    - 2
    - 'never'
  no-use-before-define:
    - 0
  no-console:
    - 0
  arrow-body-style:
    - 0
