---
# Eslint configure #############################################################
################################################################################
# http://eslint.org/docs/user-guide/configuring
# YAML javascript 语法： http://nodeca.github.io/js-yaml/
# https://github.com/airbnb/javascript

extends: "airbnb-base" # 扩展
env:
  commonjs: true
